# Name of the workflow
name: Deploy Website with API Token

on:
  # This workflow runs automatically on any push to the 'main' branch
  push:
    branches: ["main"]

  # This allows you to run the workflow manually from the Actions tab in GitHub
  workflow_dispatch:

# Set the necessary permissions for the workflow to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configure deployment settings
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # The deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Checkout
        uses: actions/checkout@v4
      
      # --- THIS IS THE CRITICAL STEP THAT FIXES THE ERROR ---
      # Step 2: Find the '%%HF_TOKEN%%' placeholder in index.html and replace it with your secret
      - name: Replace API Token Placeholder
        run: |
          sed -i "s|%%HF_TOKEN%%|${{ secrets.HF_TOKEN }}|g" index.html
        # This command uses the 'sed' utility to perform the search-and-replace.
        # It reads the value from the secret named HF_TOKEN that you configured in your repository settings.
          
      # Step 3: Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      # Step 4: Build the artifact (your website files) to be deployed
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the current directory (which now includes the modified index.html)
          path: '.'
          
      # Step 5: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

